// react-app/src/components/Messages.jsx
    import { useContext, useEffect, useState } from 'react';
import { MessagesContext } from '../models/messages.ts';
    //import useMessages from '../models/messages.ts';


    export default function Messages(){
        const messages = useContext(MessagesContext); 

        const [isOpen, setIsOpen] = useState(false);
        useEffect(()=> {
            messages.add({type: 'info', message: 'Welcome to the app'});
        }, []);

        return (

            <div class={`navbar-item has-dropdown notification-component ${isOpen && 'is-active'}`}>
                <a class="navbar-link" onClick = {()=> setIsOpen(!isOpen) }>
                    <span class="icon">
                        <i class="fas fa-bell"></i>
                    </span>
                    {messages.notifications.length >0 && 
                        <span class="tag is-danger ">
                            {messages.notifications.length}
                        </span>
                    }
                    
                </a>
                <div class="navbar-dropdown">
                    {messages.notifications.map((x,i) => (
                        <div class={`notification is-light is-${x.type}`} key={i}>
                            <button class="delete" onClick={()=>messages.close(i)} ></button>
                            { x.message }
                        </div>
                    ))}
                    
                </div>
            </div>

        );
        }

// client/src/components/Messages.vue
<script setup lang="ts">
    import { ref } from 'vue';
    import { useMessages } from '../models/messages';
    const messages = useMessages(); 
    const isOpen = ref(false);
</script>

<template>
    <div class="navbar-item has-dropdown" :class="{ 'is-active': isOpen }">
        <a class="navbar-link" @click=" isOpen = !isOpen ">
            <span class="icon">
                <i class="fas fa-bell"></i>
            </span>
            <span class="tag is-danger " v-if="messages.notifications.length">
                {{ messages.notifications.length }}
            </span>
        </a>
        <div class="navbar-dropdown">
            <div v-for=" (x, i) in messages.notifications" :class="`notification is-light is-${x.type}`">
                <button class="delete" @click="messages.close(i)" ></button>
                {{ x.message }}
            </div>
        </div>
    </div>
</template>

<style scoped>
        .icon {
        font-size: 1.5em;
    }
    .navbar-dropdown {
        width: max-content;
        max-width: 300px;
    }
    .notification {
        margin: .5rem;
        width: 95%;
    }
    .tag {
        position: absolute;
        font-size: .8em;
        top: .5em;
        right: 2.5em;
        height: 1.5em;
        padding: .5em;
        border-radius: 50%;
    }

</style>
